# Generated by Django 3.0.4 on 2020-04-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200327_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinstance',
            name='imprint',
        ),
        migrations.AddField(
            model_name='book',
            name='imprint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
